### ISSUE TITLE
error reces merci beaucoup de vous avoir aidé à corriger les erreurs

### ISSUE THREAD

**Issue by herlak** [ThaPwned/WCS#13]
Thank you very much for helping you corrected the mistakes
L
2019-08-13 18:10:06 - sp	-	MESSAGE	[SP] Chargement du plugin 'es_emulator'...
2019-08-13 18:10:06 - sp	-	MESSAGE	[SP] Le plugin 'es_emulator' a été chargé avec succès.
2019-08-13 18:10:07 - sp	-	MESSAGE	[SP] Chargement du plugin 'gungame'...
2019-08-13 18:10:08 - sp	-	MESSAGE	[SP] Le plugin 'gungame' a été chargé avec succès.
2019-08-13 18:10:08 - sp	-	MESSAGE	[SP] Chargement du plugin 'wcs'...
2019-08-13 18:10:09 - sp	-	WARNING	
[SP] Avertissement rencontré:
  File '../addons/source-python/plugins/wcs/core/modules/races/manager.py', line 199: UserWarning
    Unable to find the default race "". Using "undead_scourge" as temporary default
        race.

2019-08-13 18:10:09 - sp	-	MESSAGE	[SP] Le plugin 'wcs' a été chargé avec succès.

----------------------------------------------------------------------------------------
2019-08-13 18:48:00 - sp	-	MESSAGE	[SP] Chargement du plugin 'es_emulator'...
2019-08-13 18:48:01 - sp	-	MESSAGE	[SP] Le plugin 'es_emulator' a été chargé avec succès.
2019-08-13 18:48:01 - sp	-	MESSAGE	[SP] Chargement du plugin 'gungame'...
2019-08-13 18:48:02 - sp	-	MESSAGE	[SP] Le plugin 'gungame' a été chargé avec succès.
2019-08-13 18:48:02 - sp	-	MESSAGE	[SP] Chargement du plugin 'wcs'...
2019-08-13 18:48:02 - sp	-	WARNING	
[SP] Avertissement rencontré:
  File '../addons/source-python/plugins/wcs/core/modules/races/manager.py', line 199: UserWarning
    Unable to find the default race "". Using "undead_scourge" as temporary default
        race.

2019-08-13 18:48:02 - sp	-	MESSAGE	[SP] Le plugin 'wcs' a été chargé avec succès.
2019-08-13 18:53:56 - sp	-	EXCEPTION	
[SP] Une erreur s'est produite:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/events/listener.py", line 92, in fire_game_event
    callback(game_event)
  File "../addons/source-python/plugins/gungame/core/listeners.py", line 198, in _player_death
    if weapon_manager[weapon].basename != killer.level_weapon:
  File "../addons/source-python/packages/source-python/weapons/manager.py", line 93, in __getitem__
    return super().__getitem__(name)

KeyError: 'weapon_wcs_orcish_horde-chain_lightning'

2019-08-13 18:56:19 - sp	-	EXCEPTION	
[SP] Une erreur s'est produite:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/events/listener.py", line 92, in fire_game_event
    callback(game_event)
  File "../addons/source-python/plugins/gungame/core/listeners.py", line 198, in _player_death
    if weapon_manager[weapon].basename != killer.level_weapon:
  File "../addons/source-python/packages/source-python/weapons/manager.py", line 93, in __getitem__
    return super().__getitem__(name)

KeyError: 'weapon_wcs_orcish_horde-chain_lightning'

2019-08-13 19:01:28 - sp	-	EXCEPTION	
[SP] Une erreur s'est produite:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/events/listener.py", line 92, in fire_game_event
    callback(game_event)
  File "../addons/source-python/plugins/gungame/core/listeners.py", line 198, in _player_death
    if weapon_manager[weapon].basename != killer.level_weapon:
  File "../addons/source-python/packages/source-python/weapons/manager.py", line 93, in __getitem__
    return super().__getitem__(name)

KeyError: 'weapon_wcs_undead_scourge-suicide_bomber'

2019-08-13 19:01:38 - sp	-	EXCEPTION	
[SP] Une erreur s'est produite:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/events/listener.py", line 92, in fire_game_event
    callback(game_event)
  File "../addons/source-python/plugins/gungame/core/listeners.py", line 198, in _player_death
    if weapon_manager[weapon].basename != killer.level_weapon:
  File "../addons/source-python/packages/source-python/weapons/manager.py", line 93, in __getitem__

**Comment by ThaPwned** [comment]
This is not a problem with WCS but GunGame, as it doesn't take into account non-standard weapons such as: Orcish Horde's Chain Lightning and Undead Scourge's Suicide Bomber.

**Comment by herlak** [comment]
chaque tentative, n'a pas réussi à exécuter wcs quelqu'un m aider de configurer le fichier races.json et items.json 
File '../addons/source-python/plugins/wcs/core/modules/races/manager.py', line 199: UserWarning
Unable to find the default race "". Using "undead_scourge" as temporary default
race.
j'ai copier l'info de guide le message de ereur change  "[SP] Avertissement rencontré:
  File '../addons/source-python/plugins/wcs/core/modules/races/manager.py', line 203: UserWarning
    No races found (ESC: True) - limited access."

  [GunGame] Initializing (version 1.3.0)...
    [1/10] Parsing weapon orders...
    [2/10] Creating events...
    [3/10] Registering commands...
    [4/10] Starting sound system...
    [5/10] Loading database...
    [6/10] Executing configuration files...
    [7/10] Defining game rules...
    [8/10] Gathering player settings...
    [9/10] Importing game-specific functionality...
    [10/10] Adding 'gungame' server tag...
  [GunGame] Load completed. Restarting game...
[SP] Le plugin 'gungame' a été chargé avec succès.
[SP] Chargement du plugin 'wcs'...

[SP] Avertissement rencontré:
  File '../addons/source-python/plugins/wcs/core/modules/races/manager.py', line 203: UserWarning
    No races found (ESC: True) - limited access.

[SP] Le plugin 'wcs' a été chargé avec succès.
[EventScripts] Loaded wcs/races
[EventScripts] Loaded wcs/races/warden
[EventScripts] Loaded wcs/races/archmage_proudmoore
[EventScripts] Loaded wcs/races/blood_mage
[EventScripts] Loaded wcs/races/human_alliance
[EventScripts] Loaded wcs/races/night_elves
[EventScripts] Loaded wcs/races/orcish_horde
[EventScripts] Loaded wcs/races/shadow_hunter
[EventScripts] Loaded wcs/races/undead_scourge
[EventScripts] Loaded wcs/races/crypt_lord
[EventScripts] Loaded wcs/races/flame_predator
[EventScripts] Loaded wcs/races/succubus_hunter
ConVarRef dev_loadtime_map_start doesn't point to an existing ConVar
maxplayers set to 16
Initializing Steam libraries for secure Internet server
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Modifying bin/steamclient_valve.so
Setting breakpad minidump AppID = 240
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Setting breakpad minidump AppID = 232330
---------------------------------------------
--------------------------------------------
les 2 dossier  races items j'ai telecharger de ici https://github.com/ThaPwned/WCS-Contents
est je remet dons wcs/modules
races qui exécuter  dons plugins/es_emulator/eventscripts/wcs/
avec autoexec.cfg 
le fichier defult_races.ini dons cfg/source-python/wcs  " et tou jours le meme probleme jame joueur css avec gugame  bkp  probleme avec celui la 
j'ai aussi test gungame 1.2.16.0 avec sourcemode war3source stable 100%
en fin merci pour vous aide et bon travail.

**Comment by ThaPwned** [comment]
> chaque tentative, n'a pas réussi à exécuter wcs quelqu'un m aider de configurer le fichier races.json et items.json
File '../addons/source-python/plugins/wcs/core/modules/races/manager.py', line 199: UserWarning
Unable to find the default race "". Using "undead_scourge" as temporary default
race.

That warning is safe to ignore. If you want to remove it, simply set the `wcs_default_race` variable in `config.cfg` file to the race you want to be the default one.
> j'ai copier l'info de guide le message de ereur change "[SP] Avertissement rencontré:
File '../addons/source-python/plugins/wcs/core/modules/races/manager.py', line 203: UserWarning
No races found (ESC: True) - limited access."

That's only to let you know it didn't find any races. Some things won't work without races, so it disables those features until there's races loaded.

> les 2 dossier races items j'ai telecharger de ici https://github.com/ThaPwned/WCS-Contents
est je remet dons wcs/modules
races qui exécuter dons plugins/es_emulator/eventscripts/wcs/
avec autoexec.cfg
le fichier defult_races.ini dons cfg/source-python/wcs " et tou jours le meme probleme jame joue css avec gugame bkp probleme avec celui la
j'ai aussi test gungame 1.2.16.0 avec sourcemode war3source stable 100%
en fin merci pour vous aide et bon travail.

As I don't speak french, and the Google translation of this didn't make much sense to me, I'm not sure how I'd be able to help you. If you're talking about stability, this WCS should be the most stable one available.

**Comment by herlak** [comment]
after your help wcs became steady and without any mistakes Thank you
 The mistake was from GUNGAME Please fix it and wait for updates
THANKS GOOD JOB
