### ISSUE TITLE
Errors loading old races from 0.78

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [ThaPwned/WCS#2]
[SP] Successfully loaded plugin 'wcs'.
[EventScripts] Loaded wcs/modules/races
[EventScripts] Loaded wcs/modules/items
Tried to look up command wcs_nearcoord as if it were a variable.

[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 189, in command
    command.run(argv, args, exp)
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/cmds/__init__.py", line 140, in run
    self.method(**_args)
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/cmds/addons.py", line 20, in load
    es.load(addonname)
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/monkeypatch.py", line 28, in load
    load(addonname)
  File "../addons/source-python/plugins/es_emulator/helpers.py", line 206, in wrapper
    return func(c)
  File "../addons/source-python/plugins/es_emulator/eventscripts/es_C.py", line 2155, in load
    es.loadModuleAddon(argv[1])
  File "../addons/source-python/plugins/es_emulator/eventscripts/es.py", line 443, in loadModuleAddon
    addons.load(newaddon)
  File "../addons/source-python/plugins/es_emulator/eventscripts/es.py", line 242, in load
    addon.load()
  File "../addons/source-python/plugins/es_emulator/eventscripts/wcs/modules/items/nearcoord/nearcoord.py", line 6, in load
    registerServerCommand('wcs_nearcoord', register, '')
  File "../addons/source-python/plugins/es_emulator/eventscripts/_libs/python/cmdlib.py", line 141, in registerServerCommand
    cmd_manager.registerServerCommand(*a, **kw)
  File "../addons/source-python/plugins/es_emulator/eventscripts/_libs/python/cmdlib.py", line 37, in registerServerCommand
PreMinidumpCallback: updating dump comment
./srcds_run: line 318:  6533 Segmentation fault      $HL_CMD

**Comment by ThaPwned** [comment]
Hmm, seems like WCS loads fine. Is there any interesting messages before `[SP] Successfully loaded plugin 'wcs'.` that could be of use?
It appears that nearcoord.py isn't too happy about being loaded. It might be because WCS already registers a `wcs_nearcoord` command. Could you try without it, and see what happens?
