### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by NosferatuJoe** [ThaPwned/WCS#60]
I found some exceptions that got caught on our server launch with 20+ players on, giving some more log feedback.
Just reporting them here to keep track of them.
```
2021-03-26 17:12:52 - sp	-	EXCEPTION	
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/commands/typed.py", line 594, in on_command
    result = cls.on_clean_command(info, command_node, args)
  File "../addons/source-python/packages/source-python/commands/typed.py", line 612, in on_clean_command
    return command_node.callback(command_info, *cleaned_args)
  File "../addons/source-python/plugins/wcs/core/helpers/esc/commands.py", line 1444, in wcs_xcentertell_command
    players, message = _format_message(userid, name, args)
  File "../addons/source-python/plugins/wcs/core/helpers/esc/commands.py", line 317, in _format_message
    tokens[args[i]] = args[i + 1]

IndexError: tuple index out of range
```

-> ThaPwned: The first exception is caused by a race using wcs_xcentertell but uses an odd number of arguments
Eg.: `wcs_xcentertell <userid> <name> argument1 value1 argument2 value2 argument3"

**Comment by NosferatuJoe** [comment]
I know this error is effect related but I really wonder if some of the clamping values are correct and if it matters that it has out of range values. Have these clamping values been tested, what happens if an effect goes over it? Some effects have higher values and still seem to work fine.

```
Mar 26 23:34:17:  DataTable warning: : Out-of-range value (130.000000) in SendPropFloat 'm_fWidth', clamping.
Mar 26 23:34:17:  DataTable warning: : Out-of-range value (130.000000) in SendPropFloat 'm_fEndWidth', clamping.
```
