### ISSUE TITLE
turning off race clantag issue

### ISSUE THREAD

**Issue by NosferatuJoe** [ThaPwned/WCS#61]
Turning off race clantag doesn't fully work. Some people will still have a race clantag present, not sure why this occurs nor can I find any exceptions on this.

**Comment by NosferatuJoe** [comment]
Just found a ton of these errors:

```
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/listeners/tick.py", line 80, in _tick
    self.pop(0).execute()
  File "../addons/source-python/packages/source-python/listeners/tick.py", line 161, in execute
    return self.callback(*self.args, **self.kwargs)
  File "../addons/source-python/packages/source-python/listeners/tick.py", line 606, in _execute
    self.callback(*self.args, **self.kwargs)
  File "../addons/source-python/packages/source-python/menus/queue.py", line 239, in _radio_refresh
    queue._refresh()
  File "../addons/source-python/packages/source-python/menus/queue.py", line 105, in _refresh
    menu._refresh(self._index)
  File "../addons/source-python/packages/source-python/menus/base.py", line 104, in _refresh
    self._send(player_index)
  File "../addons/source-python/packages/source-python/menus/radio.py", line 120, in _send
    ShowMenu(*self._build(player_index)).send(player_index)
  File "../addons/source-python/packages/source-python/menus/base.py", line 114, in _build
    self.build_callback(self, player_index)
  File "../addons/source-python/plugins/wcs/core/menus/build.py", line 501, in raceinfo_skills_detail_menu_build
    race_name = wcsplayer.data['_internal_raceinfo']

KeyError: '_internal_raceinfo'


2021-03-28 00:46:46 - sp	-	EXCEPTION	
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/listeners/tick.py", line 80, in _tick
    self.pop(0).execute()
  File "../addons/source-python/packages/source-python/listeners/tick.py", line 161, in execute
    return self.callback(*self.args, **self.kwargs)
  File "../addons/source-python/packages/source-python/listeners/tick.py", line 606, in _execute
    self.callback(*self.args, **self.kwargs)
  File "../addons/source-python/packages/source-python/menus/queue.py", line 239, in _radio_refresh
    queue._refresh()
  File "../addons/source-python/packages/source-python/menus/queue.py", line 105, in _refresh
    menu._refresh(self._index)
  File "../addons/source-python/packages/source-python/menus/base.py", line 104, in _refresh
    self._send(player_index)
  File "../addons/source-python/packages/source-python/menus/radio.py", line 120, in _send
    ShowMenu(*self._build(player_index)).send(player_index)
  File "../addons/source-python/packages/source-python/menus/base.py", line 114, in _build
    self.build_callback(self, player_index)
  File "../addons/source-python/plugins/wcs/core/menus/build.py", line 501, in raceinfo_skills_detail_menu_build
    race_name = wcsplayer.data['_internal_raceinfo']

KeyError: '_internal_raceinfo'


2021-03-28 00:46:47 - sp	-	EXCEPTION	
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/listeners/tick.py", line 80, in _tick
    self.pop(0).execute()
  File "../addons/source-python/packages/source-python/listeners/tick.py", line 161, in execute
    return self.callback(*self.args, **self.kwargs)
  File "../addons/source-python/packages/source-python/listeners/tick.py", line 606, in _execute
    self.callback(*self.args, **self.kwargs)
  File "../addons/source-python/packages/source-python/menus/queue.py", line 239, in _radio_refresh
    queue._refresh()
  File "../addons/source-python/packages/source-python/menus/queue.py", line 105, in _refresh
    menu._refresh(self._index)
  File "../addons/source-python/packages/source-python/menus/base.py", line 104, in _refresh
    self._send(player_index)
  File "../addons/source-python/packages/source-python/menus/radio.py", line 120, in _send
    ShowMenu(*self._build(player_index)).send(player_index)
  File "../addons/source-python/packages/source-python/menus/base.py", line 114, in _build
    self.build_callback(self, player_index)
  File "../addons/source-python/plugins/wcs/core/menus/build.py", line 501, in raceinfo_skills_detail_menu_build
    race_name = wcsplayer.data['_internal_raceinfo']

KeyError: '_internal_raceinfo'
```

**Comment by NosferatuJoe** [comment]
![image](https://user-images.githubusercontent.com/69318638/112863589-4b334c00-90b7-11eb-9037-05b015bc2c1e.png)


As you can see race tags are still assigned although it's turned off in the settings.

**Comment by NosferatuJoe** [comment]
![image](https://user-images.githubusercontent.com/69318638/112865212-d4974e00-90b8-11eb-8d56-2155cf7e3e81.png)
Apparently the function works for bots but not for players.
