### ISSUE TITLE
Raceinfo menu exception (database related?)

### ISSUE THREAD

**Issue by NosferatuJoe** [ThaPwned/WCS#62]
I'm having a WCS not loaded yet issue and I think it's because of this exception, since it's getting spammed:

```
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/listeners/tick.py", line 80, in _tick
    self.pop(0).execute()
  File "../addons/source-python/packages/source-python/listeners/tick.py", line 161, in execute
    return self.callback(*self.args, **self.kwargs)
  File "../addons/source-python/packages/source-python/listeners/tick.py", line 606, in _execute
    self.callback(*self.args, **self.kwargs)
  File "../addons/source-python/packages/source-python/menus/queue.py", line 239, in _radio_refresh
    queue._refresh()
  File "../addons/source-python/packages/source-python/menus/queue.py", line 105, in _refresh
    menu._refresh(self._index)
  File "../addons/source-python/packages/source-python/menus/base.py", line 104, in _refresh
    self._send(player_index)
  File "../addons/source-python/packages/source-python/menus/radio.py", line 120, in _send
    ShowMenu(*self._build(player_index)).send(player_index)
  File "../addons/source-python/packages/source-python/menus/base.py", line 114, in _build
    self.build_callback(self, player_index)
  File "../addons/source-python/plugins/wcs/core/menus/build.py", line 501, in raceinfo_skills_detail_menu_build
    race_name = wcsplayer.data['_internal_raceinfo']

KeyError: '_internal_raceinfo'
```

**Comment by NosferatuJoe** [comment]
```
2021-03-28 00:57:38 - sp	-	EXCEPTION	
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/commands/auth.py", line 44, in __call__
    return self.callback(*args)
  File "../addons/source-python/packages/source-python/menus/queue.py", line 267, in _menuselect_callback
    _radio_queues[index]._select(choice)
  File "../addons/source-python/packages/source-python/menus/queue.py", line 126, in _select
    next_menu = active_menu._select(self._index, choice)
  File "../addons/source-python/packages/source-python/menus/radio.py", line 113, in _select
    self._player_pages[player_index].options[choice_index])

KeyError: 2
```

**Comment by NosferatuJoe** [comment]
![image](https://user-images.githubusercontent.com/69318638/112827561-caf8f080-908e-11eb-9acc-8808b1d7824e.png)

**Comment by NosferatuJoe** [comment]
This issue is probably trigged by this problem: #63
