### ISSUE TITLE
[URGENT] SQLite Database issue -> WCS is not ready

### ISSUE THREAD

**Issue by NosferatuJoe** [ThaPwned/WCS#63]
There is an issue where the database will create a ton of null records, essentially flooding the database and causing massive server lagg spikes & crashes.

This might be due to the latest commits where database edits have been made. I hope this can be resolved quickly since this issue renders WCS almost useless.

Also after x amount of uptime the WCS mod will stop loading and report "WCS is not ready, please wait." in chat whenever you try to use a command.

**Comment by NosferatuJoe** [comment]
Here a screenshot of a new database that is being used. Notice the amount of lists and "None" records:

![image](https://user-images.githubusercontent.com/69318638/112893991-a0815480-90db-11eb-9f7a-681508dc9d1b.png)

**Comment by NosferatuJoe** [comment]
```
2021-04-03 16:22:24 - sp	-	EXCEPTION	
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/wcs/core/database/thread.py", line 231, in _tick
    callback(result)
  File "../addons/source-python/plugins/wcs/core/players/entity.py", line 317, in _query_get_player
    raise RuntimeError(f'Tried to insert a player\'s data more than once ({self.accountid} - {result["name"]}')

RuntimeError: Tried to insert a player's data more than once (None - None


2021-04-03 16:22:24 - sp	-	EXCEPTION	
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/wcs/core/database/thread.py", line 231, in _tick
    callback(result)
  File "../addons/source-python/plugins/wcs/core/players/entity.py", line 317, in _query_get_player
    raise RuntimeError(f'Tried to insert a player\'s data more than once ({self.accountid} - {result["name"]}')

RuntimeError: Tried to insert a player's data more than once (None - None


2021-04-03 16:22:24 - sp	-	EXCEPTION	
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/wcs/core/database/thread.py", line 231, in _tick
    callback(result)
  File "../addons/source-python/plugins/wcs/core/players/entity.py", line 317, in _query_get_player
    raise RuntimeError(f'Tried to insert a player\'s data more than once ({self.accountid} - {result["name"]}')

RuntimeError: Tried to insert a player's data more than once (None - None


2021-04-03 16:22:24 - sp	-	EXCEPTION	
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/wcs/core/database/thread.py", line 231, in _tick
    callback(result)
  File "../addons/source-python/plugins/wcs/core/players/entity.py", line 317, in _query_get_player
    raise RuntimeError(f'Tried to insert a player\'s data more than once ({self.accountid} - {result["name"]}')

RuntimeError: Tried to insert a player's data more than once (None - None


2021-04-03 16:22:24 - sp	-	EXCEPTION	
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/wcs/core/database/thread.py", line 231, in _tick
    callback(result)
  File "../addons/source-python/plugins/wcs/core/players/entity.py", line 317, in _query_get_player
    raise RuntimeError(f'Tried to insert a player\'s data more than once ({self.accountid} - {result["name"]}')

RuntimeError: Tried to insert a player's data more than once (None - None


2021-04-03 16:22:24 - sp	-	EXCEPTION	
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/wcs/core/database/thread.py", line 231, in _tick
    callback(result)
  File "../addons/source-python/plugins/wcs/core/players/entity.py", line 317, in _query_get_player
    raise RuntimeError(f'Tried to insert a player\'s data more than once ({self.accountid} - {result["name"]}')

RuntimeError: Tried to insert a player's data more than once (None - None


2021-04-03 16:22:24 - sp	-	EXCEPTION	
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/wcs/core/database/thread.py", line 231, in _tick
    callback(result)
  File "../addons/source-python/plugins/wcs/core/players/entity.py", line 317, in _query_get_player
    raise RuntimeError(f'Tried to insert a player\'s data more than once ({self.accountid} - {result["name"]}')

RuntimeError: Tried to insert a player's data more than once (None - None
```

I also noticed that this event increased the server's RAM with 200MB or so.
