### ISSUE TITLE
WCS not parsing some races

### ISSUE THREAD

**Issue by NosferatuJoe** [ThaPwned/WCS#64]
I tried migrating my server to another host and stumbled upon this issue:

```
[SP] Loading plugin 'es_emulator'...
[EventScripts] Temporary: Setting the host's IP variable from the command-line.
[EventScripts] Loaded esc
[SP] Successfully loaded plugin 'es_emulator'.
[SP] Loading plugin 'wcs'...

[SP] Encountered a Warning:
  File '../addons/source-python/plugins/wcs/core/modules/oldesc.py', line 219: UserWarning
    Unable to properly parse the race "wcs_lng_undead_scourge" due to the following
        exception:


[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/wcs/core/modules/oldesc.py", line 147, in parse_ini_races
    skillnames = (_esc_strings[fixed_name][data['skillnames'][8:]].get_string('en') if data['skillnames'].startswith('wcs_lng_') else data['skillnames']).split('|')

KeyError: 'undead_scourge'



[SP] Encountered a Warning:
  File '../addons/source-python/plugins/wcs/core/modules/oldesc.py', line 219: UserWarning
    Unable to properly parse the race "wcs_lng_human_alliance" due to the following
        exception:


[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/wcs/core/modules/oldesc.py", line 147, in parse_ini_races
    skillnames = (_esc_strings[fixed_name][data['skillnames'][8:]].get_string('en') if data['skillnames'].startswith('wcs_lng_') else data['skillnames']).split('|')

KeyError: 'human_alliance'



[SP] Encountered a Warning:
  File '../addons/source-python/plugins/wcs/core/modules/oldesc.py', line 219: UserWarning
    Unable to properly parse the race "wcs_lng_orcish_horde" due to the following
        exception:


[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/wcs/core/modules/oldesc.py", line 147, in parse_ini_races
    skillnames = (_esc_strings[fixed_name][data['skillnames'][8:]].get_string('en') if data['skillnames'].startswith('wcs_lng_') else data['skillnames']).split('|')

KeyError: 'orcish_horde'



[SP] Encountered a Warning:
  File '../addons/source-python/plugins/wcs/core/modules/oldesc.py', line 219: UserWarning
    Unable to properly parse the race "wcs_lng_night_elves" due to the following
        exception:


[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/wcs/core/modules/oldesc.py", line 147, in parse_ini_races
    skillnames = (_esc_strings[fixed_name][data['skillnames'][8:]].get_string('en') if data['skillnames'].startswith('wcs_lng_') else data['skillnames']).split('|')

KeyError: 'night_elves'



[SP] Encountered a Warning:
  File '../addons/source-python/plugins/wcs/core/modules/oldesc.py', line 219: UserWarning
    Unable to properly parse the race "wcs_lng_blood_mage" due to the following
        exception:


[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/wcs/core/modules/oldesc.py", line 147, in parse_ini_races
    skillnames = (_esc_strings[fixed_name][data['skillnames'][8:]].get_string('en') if data['skillnames'].startswith('wcs_lng_') else data['skillnames']).split('|')

KeyError: 'blood_mage'



[SP] Encountered a Warning:
  File '../addons/source-python/plugins/wcs/core/modules/oldesc.py', line 219: UserWarning
    Unable to properly parse the race "wcs_lng_archmage_proudmoore" due to the
        following exception:


[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/wcs/core/modules/oldesc.py", line 147, in parse_ini_races
    skillnames = (_esc_strings[fixed_name][data['skillnames'][8:]].get_string('en') if data['skillnames'].startswith('wcs_lng_') else data['skillnames']).split('|')

KeyError: 'archmage_proudmoore'



[SP] Encountered a Warning:
  File '../addons/source-python/plugins/wcs/core/modules/oldesc.py', line 219: UserWarning
    Unable to properly parse the race "wcs_lng_shadow_hunter" due to the following
        exception:


[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/wcs/core/modules/oldesc.py", line 147, in parse_ini_races
    skillnames = (_esc_strings[fixed_name][data['skillnames'][8:]].get_string('en') if data['skillnames'].startswith('wcs_lng_') else data['skillnames']).split('|')

KeyError: 'shadow_hunter'



[SP] Encountered a Warning:
  File '../addons/source-python/plugins/wcs/core/modules/oldesc.py', line 219: UserWarning
    Unable to properly parse the race "wcs_lng_warden" due to the following
        exception:


[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/wcs/core/modules/oldesc.py", line 147, in parse_ini_races
    skillnames = (_esc_strings[fixed_name][data['skillnames'][8:]].get_string('en') if data['skillnames'].startswith('wcs_lng_') else data['skillnames']).split('|')

KeyError: 'warden'



[SP] Encountered a Warning:
  File '../addons/source-python/plugins/wcs/core/modules/oldesc.py', line 219: UserWarning
    Unable to properly parse the race "wcs_lng_crypt_lord" due to the following
        exception:


[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/wcs/core/modules/oldesc.py", line 147, in parse_ini_races
    skillnames = (_esc_strings[fixed_name][data['skillnames'][8:]].get_string('en') if data['skillnames'].startswith('wcs_lng_') else data['skillnames']).split('|')

KeyError: 'crypt_lord'



[SP] Encountered a Warning:
  File '../addons/source-python/plugins/wcs/core/modules/oldesc.py', line 219: UserWarning
    Unable to properly parse the race "wcs_lng_flame_predator" due to the following
        exception:


[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/wcs/core/modules/oldesc.py", line 147, in parse_ini_races
    skillnames = (_esc_strings[fixed_name][data['skillnames'][8:]].get_string('en') if data['skillnames'].startswith('wcs_lng_') else data['skillnames']).split('|')

KeyError: 'flame_predator'



[SP] Encountered a Warning:
  File '../addons/source-python/plugins/wcs/core/modules/oldesc.py', line 219: UserWarning
    Unable to properly parse the race "wcs_lng_succubus_hunter" due to the following
        exception:


[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/wcs/core/modules/oldesc.py", line 147, in parse_ini_races
    skillnames = (_esc_strings[fixed_name][data['skillnames'][8:]].get_string('en') if data['skillnames'].startswith('wcs_lng_') else data['skillnames']).split('|')

KeyError: 'succubus_hunter'



[SP] Encountered a Warning:
  File '../addons/source-python/plugins/wcs/core/modules/races/manager.py', line 227: UserWarning
    Unable to find the default race "undead_scourge". Using "athena" as temporary
        default race.

[SP] Successfully loaded plugin 'wcs'.
```

I've tried everything including fresh installs and adding the race packs on top but nothing seems to help. The odd thing is that it only happens to the translated standard race pack and not to the others. Any clue why this is happening?

**Comment by NosferatuJoe** [comment]
Never mind, I forgot to transfer over the proper translations files for the standard race pack. My bad :/
